version: 2
updates:
  - package-ecosystem: "docker"
    directory: "./0.8.0/"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
