name: Publish

on:
  release:
    types: [published]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        cd ${{ steps.iodine.outputs.version }}/
        docker build . -t iodine

    - name: Tag image
      run: |
        docker tag iodine dmachard/iodine:${{ github.event.release.tag_name }}
        docker tag iodine dmachard/iodine:latest

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/iodine:${{ github.event.release.tag_name }}
        docker push dmachard/iodine:latest